### ISSUE TITLE
Undo does not work correctly

### ISSUE THREAD

**Issue by TkPegatron** [Hexafag/2048#1]
CTRL+Z Does not reverse states correctly. The method behaves strangely after ten + turns.

EG: 
Jumping back more than one turn. unable to jump back 10 more turns after moving forward.

Suggested fix: 
Expand the array and unlimit the incrementation of 'savedStates'.

**Comment by Hexafag** [comment]
it also does not decrement the turn couter properly

**Comment by Hexafag** [comment]
also scratch what i said earlier
